### PR TITLE
WBCAMS-377-fix-federal-jobs-filter

### PR DESCRIPTION
**Pull request by jonathan-longe**
Create ElasticSearch query string to search for federal government jobs using the source URL.

Screenshot (33)

### CODE REVIEW

**Review by infojunkie — COMMENTED** [review]
What happens if the Employer type was 2 ? Will those jobs disappear from the filter ?

**Comment by jonathan-longe** [comment]
> What happens if the Employer type was 2 ? Will those jobs disappear from the filter ?

I removed the `EmployerTypeId` filter as that filter doesn't yield any results in DEV or PROD and I can't find an attribute by that name in any XML examples I checked.  My reading of the ticket comments suggests relying on the source URL, but I'm happy to add `EmployerTypeId` back if you think it appropriate.

**Comment by jonathan-longe** [comment]
Clarification: "... I can't find an attribute by that name in any __relevant__ XML examples I checked."

**Comment by infojunkie** [comment]
> Clarification: "... I can't find an attribute by that name in any relevant XML examples I checked."

A few lines below https://github.com/bcgov/workbc-jb/pull/111/files#diff-5cb314c042ff43209870e4bba257ebd3482b9da3679eb0c4d58d7fceaf5ccf84L740 the same attribute is used.

This attribute is sourced from the `employer_type_id` of the XML feed: https://github.com/bcgov/workbc-jb/blob/60b06e4f436e0cf47379e9806cd7ae5b9d8bf975/src/WorkBC.ElasticSearch.Indexing/Services/XmlParsingServiceFederal.cs#L86

I would feel more comfortable if both conditions were OR'd.

**Comment by jonathan-longe** [comment]
> A few lines below https://github.com/bcgov/workbc-jb/pull/111/files#diff-5cb314c042ff43209870e4bba257ebd3482b9da3679eb0c4d58d7fceaf5ccf84L740 the same attribute is used.

Yes, that's true but I noticed that filter is also broken.  It returns only a single job in DEV and PROD where the employer is the University of British Columbia -- not the Province -- and it fails to return numerous jobs it should return from the Ministry of Forests etc.

> This attribute is sourced from the `employer_type_id` of the XML feed:

Yes, I'm aware of that, but that attribute is only supplied when the source is the federal jobs board and ironically all our federal government jobs are being imported from the Talent / Neuron API -- not the federal jobs API.

**Review by infojunkie — APPROVED** [review]
Go ahead and merge this, we'll deal with the `EmployerTypeId` in another ticket.

**Pull request merged**
